print ("Wassup buddy!! v1")
print ("Wassup buddy!! v2 launched")
print ("Checking if the email notification service is working!")
print ("There is an error on this code, You will get an email via email.")
print ("Last syntax error was removed and the all the issues has been resolved")
